version: 2
log-file: "/tmp/efm.log"
log-level: 1
root-markers:
  - .git/
  - package.json

tools:
  eslint: &eslint
    lint-command: 'eslint_d -f visualstudio --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"

languages:
  javascript:
    - <<: *eslint

  typescript:
    - <<: *eslint
